name: ipeo_venv
channels:
  - defaults
dependencies:
  - python=3.9.10  
  - pip
  - pip:
    - affine==2.4.0
    - anyio==4.7.0
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - asttokens==3.0.0
    - async-lru==2.0.4
    - attrs==24.3.0
    - babel==2.16.0
    - beautifulsoup4==4.12.3
    - bleach==6.2.0
    - certifi==2024.12.14
    - cffi==1.17.1
    - chardet==4.0.0
    - charset-normalizer==3.4.0
    - click==8.1.7
    - click-plugins==1.1.1
    - cligj==0.7.2
    - comm==0.2.2
    - contourpy==1.3.0
    - cycler==0.12.1
    - dbus-python==1.2.18
    - debugpy==1.8.11
    - decorator==4.4.2
    - defusedxml==0.7.1
    - distlib==0.3.2
    - efficientnet-pytorch==0.7.1
    - ethtool==0.15
    - exceptiongroup==1.2.2
    - executing==2.1.0
    - fastjsonschema==2.21.1
    - filelock==3.7.1
    - fonttools==4.55.3
    - fqdn==1.5.1
    - fsspec==2024.10.0
    - gdown==5.2.0
    - gpg==1.15.1
    - h11==0.14.0
    - httpcore==1.0.7
    - httpx==0.28.1
    - huggingface-hub==0.27.1
    - idna==2.10
    - importlib_metadata==8.5.0
    - importlib_resources==6.4.5
    - iniparse==0.4
    - iotop==0.6
    - ipykernel==6.29.5
    - ipython==8.18.1
    - ipywidgets==8.1.5
    - isoduration==20.11.0
    - jedi==0.19.2
    - Jinja2==3.1.4
    - joblib==1.4.2
    - json5==0.10.0
    - jsonpointer==3.0.0
    - jsonschema==4.23.0
    - jsonschema-specifications==2024.10.1
    - jupyter==1.1.1
    - jupyter-console==6.6.3
    - jupyter-events==0.11.0
    - jupyter-lsp==2.2.5
    - jupyter_client==8.6.3
    - jupyter_core==5.7.2
    - jupyter_server==2.14.2
    - jupyter_server_terminals==0.5.3
    - jupyterlab==4.3.4
    - jupyterlab_pygments==0.3.0
    - jupyterlab_server==2.27.3
    - jupyterlab_widgets==3.0.13
    - kiwisolver==1.4.7
    - libcomps==0.1.18
    - MarkupSafe==3.0.2
    - matplotlib==3.9.4
    - matplotlib-inline==0.1.7
    - mercurial==6.1.4
    - mistune==3.0.2
    - mpmath==1.3.0
    - munch==4.0.0
    - nbclient==0.10.2
    - nbconvert==7.16.4
    - nbformat==5.10.4
    - nest-asyncio==1.6.0
    - networkx==3.2.1
    - nftables==0.1
    - notebook==7.3.1
    - notebook_shim==0.2.4
    - numpy==2.0.2
    - nvidia-cublas-cu12==12.4.5.8
    - nvidia-cuda-cupti-cu12==12.4.127
    - nvidia-cuda-nvrtc-cu12==12.4.127
    - nvidia-cuda-runtime-cu12==12.4.127
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.2.1.3
    - nvidia-curand-cu12==10.3.5.147
    - nvidia-cusolver-cu12==11.6.1.9
    - nvidia-cusparse-cu12==12.3.1.170
    - nvidia-nccl-cu12==2.21.5
    - nvidia-nvjitlink-cu12==12.4.127
    - nvidia-nvtx-cu12==12.4.127
    - overrides==7.7.0
    - packaging==24.2
    - pandocfilters==1.5.1
    - parso==0.8.4
    - pcp==5.0
    - pexpect==4.9.0
    - pillow==11.0.0
    - platformdirs==2.5.4
    - pretrainedmodels==0.7.4
    - prometheus_client==0.21.1
    - prompt_toolkit==3.0.48
    - psutil==6.1.0
    - ptyprocess==0.7.0
    - pure_eval==0.2.3
    - pycparser==2.22
    - Pygments==2.18.0
    - PyGObject==3.40.1
    - pyinotify==0.9.6
    - pyparsing==2.4.7
    - PySocks==1.7.1
    - python-dateutil==2.9.0.post0
    - python-dmidecode==3.12.2
    - python-json-logger==3.2.1
    - PyYAML==5.4.1
    - pyzmq==26.2.0
    - rasterio==1.4.3
    - referencing==0.35.1
    - requests==2.32.3
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rpds-py==0.22.3
    - rpm==4.16.1.3
    - safetensors==0.5.2
    - scikit-learn==1.6.1
    - scipy==1.13.1
    - segmentation_models_pytorch==0.4.0
    - selinux==3.3
    - Send2Trash==1.8.3
    - sepolicy==3.3
    - setools==4.4.0
    - six==1.15.0
    - sklearn==0.0
    - sniffio==1.3.1
    - soupsieve==2.6
    - stack-data==0.6.3
    - subscription-manager==1.29.26.1
    - sympy==1.13.1
    - terminado==0.18.1
    - threadpoolctl==3.5.0
    - timm==1.0.13
    - tinycss2==1.4.0
    - tomli==2.2.1
    - torch==2.5.1
    - torchvision==0.20.1
    - tornado==6.4.2
    - tqdm==4.67.1
    - traitlets==5.14.3
    - triton==3.1.0
    - types-python-dateutil==2.9.0.20241206
    - typing_extensions==4.12.2
    - uri-template==1.3.0
    - urllib3==1.26.5
    - virtualenv==20.20.0
    - wcwidth==0.2.13
    - webcolors==24.11.1
    - webencodings==0.5.1
    - websocket-client==1.8.0
    - widgetsnbextension==4.0.13
    - zipp==3.21.0
